<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>${projectInfo.groupId}</groupId>
    <artifactId>${projectInfo.artifactId}-parent</artifactId>
    <version>${projectInfo.version}</version>
    <name>${projectInfo.name}</name>
    <description>${projectInfo.description}</description>
    <packaging>pom</packaging>

    <modules>
        <module>${projectInfo.artifactId}</module>
        <module>${projectInfo.artifactId}-client</module>
    </modules>

    <properties>
        <version.spring.boot>${projectInfo.springBootVersion}</version.spring.boot>
        <version.spring.cloud>${projectInfo.springCloudVersion}</version.spring.cloud>
        <version.jdk>1.8</version.jdk>
        <version.mapstruct>1.2.0.Final</version.mapstruct>
        <version.apache.poi>3.13</version.apache.poi>
        <version.keycloak>7.0.0</version.keycloak>
        <squareup.okhttp3.version>3.8.1</squareup.okhttp3.version>
        <version.swagger>2.9.2</version.swagger>
        <version.swagger.models>1.5.21</version.swagger.models>
        <version.jaeger.starter>2.0.3</version.jaeger.starter>
        <version.deepblue.base>0.0.1-SNAPSHOT</version.deepblue.base>
    </properties>

    <distributionManagement>
        <repository>
            <id>deepblue-releases</id>
            <name>deepblue-releases</name>
            <url>https://nexus.deepblueai.com/repository/deepblue-releases/</url>
        </repository>
        <snapshotRepository>
            <id>deepblue-snapshots</id>
            <name>deepblue-snapshots</name>
            <url>http://nexus.deepblueai.com/repository/deepblue-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${projectInfo.groupId}</groupId>
                <artifactId>${projectInfo.artifactId}-client</artifactId>
                <version>${r'${project.version}'}</version>
            </dependency>
            <dependency>
                <groupId>io.deepblueai</groupId>
                <artifactId>deepblueai-base</artifactId>
                <version>${r'${version.deepblue.base}'}</version>
            </dependency>
            <dependency>
                <groupId>com.github.pukkaone</groupId>
                <artifactId>logback-gelf</artifactId>
                <version>${r'${version.pukkaone.logback.gelf}'}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${r'${version.spring.cloud}'}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${r'${version.spring.boot}'}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-jdk8</artifactId>
                <version>${r'${version.mapstruct}'}</version>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${r'${version.mapstruct}'}</version>
            </dependency>
            <#list dependencies as dependency>
                <!-- ${dependency.name} -->
                <dependency>
                    <groupId>${dependency.groupId}</groupId>
                    <artifactId>${dependency.artifactId}</artifactId>
                    <version>${dependency.version}</version>
                </dependency>
            </#list>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-access</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>${r'${version.swagger}'}</version>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-models</artifactId>
            <version>${r'${version.swagger.models}'}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>${r'${project.artifactId}'}</finalName>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${r'${version.spring.boot}'}</version>
                    <configuration>
                        <finalName>${r'${project.name}'}</finalName>
                        <mainClass>${r'${start-class}'}</mainClass>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>repackage</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.mybatis.generator</groupId>
                    <artifactId>mybatis-generator-maven-plugin</artifactId>
                    <version>1.3.5</version>
                    <configuration>
                        <skip>false</skip>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>mysql</groupId>
                            <artifactId>mysql-connector-java</artifactId>
                            <version>5.1.41</version>
                        </dependency>
                        <dependency>
                            <groupId>tk.mybatis</groupId>
                            <artifactId>mapper</artifactId>
                            <version>3.4.0</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <artifactId>maven-deploy-plugin</artifactId>
                <version>2.8.2</version>
                <executions>
                    <execution>
                        <id>deploy</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.0.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.0.2</version>
                <configuration>
                    <source>${r'${version.jdk}'}</source>
                    <target>${r'${version.jdk}'}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>